version: "3.6"
services:
    prod:
        image: dhis2/im-web-client:${IMAGE_TAG:-latest}
        build:
            context: .
            args:
                REACT_APP_API_URL: ${API_URL}
        ports:
            - "8080:8080"

    dev:
        build:
            context: .
            target: builder
            args:
                REACT_APP_API_URL: ${API_URL}
        stdin_open: true
        tty: true
        volumes:
            - .:/src
        working_dir: /src
        command: yarn start
        ports:
            - "3000:3000"

    test:
        image: mcr.microsoft.com/playwright:latest
        stdin_open: true
        tty: true
        command: sh -c "yarn install --frozen-lockfile && npx playwright test"
        network_mode: host
        volumes:
            - ./:/e2e
        working_dir: /e2e
        environment:
            CI: "true"
            IM_ADMIN_USER: ${IM_ADMIN_USER}
            IM_ADMIN_PASSWORD: ${IM_ADMIN_PASSWORD}
            API_URL: ${API_URL}
            REACT_APP_API_URL: ${API_URL}
