version: '3.6'
services:
  prod:
    image: dhis2/im-web-client:${IMAGE_TAG:-latest}
    build:
      context: .
      args:
        REACT_APP_IM_API: ${IM_API}
    ports:
      - '8080:8080'

  dev:
    build:
      context: .
      target: builder
      args:
        REACT_APP_IM_API: ${IM_API}
    stdin_open: true
    tty: true
    volumes:
      - .:/src
    working_dir: /src
    command: yarn start
    ports:
      - "3000:3000"

  test:
    image: cypress/included:11.2.0
    stdin_open: true
    tty: true
    volumes:
      - .:/e2e
    working_dir: /e2e
    env_file:
      - .env
