apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/im-web-client
      docker:
        buildArgs:
          REACT_APP_API_URL: "{{ .API_URL }}"
  tagPolicy:
    inputDigest: { }
deploy:
  statusCheckDeadlineSeconds: 180
  helm:
    releases:
      - name: im-web-client-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        setValueTemplates:
          ingress:
            enabled: true
            hostname: "{{ .UI_HOSTNAME }}"
            certIssuer: cert-issuer-prod
        valuesFiles:
          - helm/data/values/{{ .CLASSIFICATION }}/values.yaml
