/* Types are generated by https://github.com/drwpow/openapi-typescript
 * which generates `paths`, `definitions`, `responses`, `operations` and
 * `external` types. Currently we are only interested in the regular
 * type declarations which are exported under the `definitions` interface.
 * We also want all types to be available directly, and not as a nested
 * data-structure. To achieve this we have some hardcoded type exports
 * below, which probably isn't the most elegant solution, but it'll do
 * for now. The consequence of this is that new exports may need to be
 * added here once the are added to the OpenAPI specifications. */

import type { definitions } from './generated-types'

// Curated list of types. May need to be updated from time to time
export type ClusterConfiguration = definitions['ClusterConfiguration']
export type Database = definitions['Database']
export type ExternalDownload = definitions['ExternalDownload']
export type Group = definitions['Group']
export type GroupWithInstances = definitions['GroupWithInstances']
// Consider renaming in OpenApi Spec
export type GroupWithDatabases = definitions['GroupsWithDatabases']
export type Instance = definitions['Instance']
export type InstanceOptionalParameter = definitions['InstanceOptionalParameter']
export type InstanceRequiredParameter = definitions['InstanceRequiredParameter']
export type Lock = definitions['Lock']
export type Stack = definitions['Stack']
export type StackOptionalParameter = definitions['StackOptionalParameter']
export type StackRequiredParameter = definitions['StackRequiredParameter']
export type Tokens = definitions['Tokens']
export type User = definitions['User']
