/* Types are generated by `openapi-typescript-codegen`. It can generate a
 * bunch of stuff but currently all we need is the models.
 * One of the types in the OpenApi spec is incorrectly named in my opinion.
 * `GroupsWithDatabases` actually describes a single group. Re-exporting
 * everything excl. this incorrectly named item is not possible without manually
 * re-exporting all named types. So we don't bother removing the incorrectly
 * named type, but just export it under the correct name too.
 * TODO: fix this name in the OpenAPI spec. */

export type * from './generated'
// Export as corrected name
export type { GroupsWithDatabases as GroupWithDatabases } from './generated'
