#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn d2-style apply --staged

# ORIGINAL ABOVE

function detect_type_changes () {
    local HAS_CHANGED_TYPES=false
    local CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
    [ -z "$CHANGED_FILES" ] && exit 0

    echo "I am the great hendrikey 1"
    echo "I am the great hendrikey 2"
    echo "I am the great hendrikey 3"
    exit 1

    # Prettify all selected files
    # echo "$CHANGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

    # Add back the modified/prettified files to staging
    # echo "$CHANGED_FILES" | xargs git add

    # exit 0
}

detect_type_changes

