#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# yarn d2-style apply --staged

# ORIGINAL ABOVE

function detect_type_changes () {
    local CHANGED_FILES=$(git diff --cached --name-only | sed 's| |\\ |g')
    echo echo "HENKIE $CHANGED_FILES"
    # [ -z "$CHANGED_FILES" ] && exit 0

    # echo "WHUT $CHANGED_FILES"

    # for FILE_NAME in CHANGED_FILES
    # do
    #     echo "FILE_HENKIE $FILE_NAME"
    # done


    # echo "OpenAPI changes detected. Please commit the updated Type definitions."
    # exit 1

    # Prettify all selected files
    # echo "$CHANGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

    # Add back the modified/prettified files to staging
    # echo "$CHANGED_FILES" | xargs git add

    # exit 0

    # let changes=0
    # while read status filename; do
    #     let changes=1
    #     # do something with this filename/status
    # done < <(git status --porcelain)
    # if ((changes)); then
    #     echo "Found changes."
    #     exit 1
    # else
    #     echo "No changes."
    #     exit 1
    # fi
}

detect_type_changes

