#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Check if staged files can be compiled (without generating js files)
echo "$FILES" | xargs ./node_modules/.bin/tsc --noEmit

# Format all staged files
# Prettier
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
# ESLint
echo "$FILES" | xargs ./node_modules/.bin/eslint --fix

# Add back the modified files to staging
echo "$FILES" | xargs git add

exit 0