apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "im-web-client.fullname" . }}
  labels:
    {{- include "im-web-client.labels" . | nindent 4 }}
data:
  API_URL: {{ .Values.apiUrl | quote }}
