kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "im-web-client.fullname" . }}
  labels:
    {{- include "im-web-client.labels" . | nindent 4 }}
data:
  IM_HOST: {{ .Values.instanceManagerHost | quote }}
