name: Playwright Tests

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    e2e:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run Playwright tests
              run: make e2e-test
              env:
                  CI: true
                  API_URL: https://dev.api.im.dhis2.org
                  REACT_APP_API_URL: https://dev.api.im.dhis2.org
                  IM_ADMIN_USER: ${{ secrets.IM_ADMIN_USER }}
                  IM_ADMIN_PASSWORD: ${{ secrets.IM_ADMIN_PASSWORD }}
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
