name: Playwright Tests
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    e2e:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test --debug
              env:
                  # Not quite sure where to read these values
                  UI_HOSTNAME: ${{ secrets.UI_HOSTNAME }}
                  USER_EMAIL: ${{ secrets.USER_EMAIL }}
                  PASSWORD: ${{ secrets.PASSWORD }}
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
