name: Playwright Tests

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
    workflow_dispatch:
        inputs:
            api_url:
                description: 'API URL target for the tests.'
                type: string
                required: true

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    e2e:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            # TODO update the default API_URL before merging
            TARGET_URL: ${{ github.event_name == 'workflow_dispatch' && inputs.api_url || 'https://devops-291.api.im.dhis2.org' }}
        steps:
            - uses: actions/checkout@v4
            - name: Run Playwright tests
              run: make e2e-test
              env:
                  CI: true
                  API_URL: ${{ env.TARGET_URL }}
                  REACT_APP_API_URL: ${{ env.TARGET_URL }}
                  USER_EMAIL: ${{ secrets.IM_E2E_TEST_USER_EMAIL }}
                  USER_PASSWORD: ${{ secrets.IM_E2E_TEST_USER_PASSWORD }}
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
