name: Test

on:
    pull_request:
        types: [ opened, labeled, synchronize, reopened ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        if: "contains(github.event.pull_request.labels.*.name, 'test')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Test
              run: |
                echo "running tests ..."
                sleep 5
                echo "tests done!"
# this change should not trigger a test run
